name: cite
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - blinker=1.9.0=pyhff2d567_0
  - brotli-python=1.2.0=py312h67db365_0
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - certifi=2025.10.5=pyhd8ed1ab_0
  - cffi=2.0.0=py312h460c074_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.0=pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - daiquiri=3.0.0=pyhd3deb0d_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - flask=3.1.2=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - iniconfig=2.3.0=pyhd8ed1ab_0
  - itsdangerous=2.2.0=pyhd8ed1ab_1
  - jansson=2.14.1=hb9d3cd8_0
  - jinja2=3.1.6=pyhd8ed1ab_0
  - ld_impl_linux-64=2.44=h1aa0949_4
  - libexpat=2.7.1=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgomp=15.2.0=h767d61c_7
  - libiconv=1.18=h3b78370_2
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libsqlite=3.50.4=h0c1763c_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libuuid=2.41.2=he9a06e4_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.15.1=h26afc86_0
  - libxml2-16=2.15.1=ha9997c6_0
  - libxslt=1.1.43=h711ed8c_1
  - libzlib=1.3.1=hb9d3cd8_2
  - lxml=6.0.2=py312h63ddcf0_1
  - markupsafe=3.0.3=py312h8a5da7c_0
  - ncurses=6.5=h2d0b736_3
  - openssl=3.5.4=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - pcre2=10.46=h1321c63_0
  - pendulum=3.1.0=py312h12e396e_0
  - pip=25.2=pyh8b19718_0
  - pluggy=1.6.0=pyhd8ed1ab_0
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha55dd90_7
  - pytest=8.4.2=pyhd8ed1ab_0
  - python=3.12.12=hd63d673_1_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python_abi=3.12=8_cp312
  - readline=8.2=h8c095d6_2
  - requests=2.32.5=pyhd8ed1ab_0
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - time-machine=2.19.0=py312h5253ce2_1
  - tk=8.6.13=noxft_hd72426e_102
  - tomli=2.3.0=pyhcf101f3_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - uwsgi=2.0.31=py312h70fdf7e_0
  - werkzeug=3.1.3=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - yaml=0.2.5=h280c20c_3
  - zipp=3.23.0=pyhd8ed1ab_0
  - zstandard=0.25.0=py312h5253ce2_0
  - zstd=1.5.7=hb8e6e7a_2
prefix: /home/servilla/miniconda3/envs/cite
